export const spacing = {
  screenX: 18,
  bottomButton: 16,
  cardRadius: 8,
  homeCardRadius: 20,
  homeCardPaddingX: 22,
  homeCardPaddingY: 22,
  homeCardContentGap: 14,
  homeListGap: 14,
  homeListPaddingTop: 42,
  homeListPaddingBottom: 22,
  inputHeight: 52,
  chipHeight: 32,
  navHeight: 76,
  homeFrameWidth: 390,
  homeFrameHeight: 844,
} as const;
